/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class AddTugasDosenView extends javax.swing.JFrame implements View{

    /**
     * Creates new form AddTugasDosenView
     */
    public AddTugasDosenView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupTipeTugas = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tFNamaTugas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tFJumlahSoal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnRadioIndividu = new javax.swing.JRadioButton();
        btnRadioKelompok = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Tugas: ");

        jLabel2.setText("Jumlah Soal: ");

        tFJumlahSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFJumlahSoalActionPerformed(evt);
            }
        });

        jLabel3.setText("Tipe Tugas: ");

        grupTipeTugas.add(btnRadioIndividu);
        btnRadioIndividu.setText("Individu");

        grupTipeTugas.add(btnRadioKelompok);
        btnRadioKelompok.setText("Kelompok");

        jLabel5.setText("Add Tugas");

        btnSubmit.setText("Submit");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tFNamaTugas)
                            .addComponent(tFJumlahSoal, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRadioIndividu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(btnRadioKelompok)
                                .addGap(37, 37, 37))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tFNamaTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tFJumlahSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnRadioIndividu)
                    .addComponent(btnRadioKelompok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBack))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tFJumlahSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFJumlahSoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFJumlahSoalActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnRadioIndividu;
    private javax.swing.JRadioButton btnRadioKelompok;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup grupTipeTugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField tFJumlahSoal;
    private javax.swing.JTextField tFNamaTugas;
    // End of variables declaration//GEN-END:variables

   
    public void addListener(ActionListener l){
        btnBack.addActionListener(l);
        btnSubmit.addActionListener(l);
        btnRadioIndividu.addActionListener(l);
        btnRadioKelompok.addActionListener(l);
        tFJumlahSoal.addActionListener(l);
        tFNamaTugas.addActionListener(l);
    
    }
    
    public JButton getBtnBack() {
        return btnBack;
    }

    public JRadioButton getBtnRadioIndividu() {
        return btnRadioIndividu;
    }

    public JRadioButton getBtnRadioKelompok() {
        return btnRadioKelompok;
    }

    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public JTextField gettFJumlahSoal() {
        return tFJumlahSoal;
    }

    public void settFJumlahSoal(String s) {
        this.tFJumlahSoal.setText(s);
    }

    public JTextField gettFNamaTugas() {
        return tFNamaTugas;
    }

    public void settFNamaTugas(String s) {
        this.tFNamaTugas.setText(s);
    }

    

}
