/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class DosenUtamaView extends javax.swing.JFrame implements View {

    /**
     * Creates new form DosenUtamaView
     */
    public DosenUtamaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnKelas = new javax.swing.JButton();
        btnAddKelas = new javax.swing.JButton();
        btnDeleteKelas = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Dosen");

        btnProfile.setText("Profile");

        btnKelas.setText("Pilih Kelas");

        btnAddKelas.setText("Add Kelas Baru");
        btnAddKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKelasActionPerformed(evt);
            }
        });

        btnDeleteKelas.setText("Delete Kelas");

        btnLogout.setText("Log Out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                                .addComponent(btnDeleteKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(btnProfile)
                .addGap(18, 18, 18)
                .addComponent(btnKelas)
                .addGap(18, 18, 18)
                .addComponent(btnAddKelas)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddKelasActionPerformed

    public void addListener(ActionListener l){
        btnAddKelas.addActionListener(l);
        btnKelas.addActionListener(l);
        btnDeleteKelas.addActionListener(l);
        btnLogout.addActionListener(l);
        btnProfile.addActionListener(l);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKelas;
    private javax.swing.JButton btnDeleteKelas;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAddKelas() {
        return btnAddKelas;
    }

    public JButton getBtnDeleteKelas() {
        return btnDeleteKelas;
    }

    public JButton getBtnKelas() {
        return btnKelas;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnProfile() {
        return btnProfile;
    }
    
}

