/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class MenuKelasUtamaDosen extends javax.swing.JFrame implements View {

    /**
     * Creates new form MenuKelasUtama
     */
    public MenuKelasUtamaDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTugas = new javax.swing.JButton();
        btnKelompok = new javax.swing.JButton();
        btnMhs = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lnamaKelas = new javax.swing.JLabel();
        btnKelas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTugas.setText("Pengelolaan Tugas");

        btnKelompok.setText("Pengelolaan Kelompok");

        btnMhs.setText("Pengelolaan Mahasiswa");

        btnBack.setText("Back");

        lnamaKelas.setText("{nama Kelas Here}");

        btnKelas.setText("Info Kelas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMhs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lnamaKelas)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lnamaKelas)
                .addGap(18, 18, 18)
                .addComponent(btnKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKelompok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMhs)
                .addGap(64, 64, 64)
                .addComponent(btnBack)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnKelompok;
    private javax.swing.JButton btnMhs;
    private javax.swing.JButton btnTugas;
    private javax.swing.JLabel lnamaKelas;
    // End of variables declaration//GEN-END:variables

    
    public void addListener(ActionListener l){
        btnBack.addActionListener(l);
        btnKelompok.addActionListener(l);
        btnMhs.addActionListener(l);
        btnTugas.addActionListener(l);
        btnKelas.addActionListener(l);
    }

    public JButton getBtnKelas() {
        return btnKelas;
    }
    
    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnKelompok() {
        return btnKelompok;
    }

    public JButton getBtnMhs() {
        return btnMhs;
    }

    public JButton getBtnTugas() {
        return btnTugas;
    }

    public void setLnamaKelas(String nama) {
        this.lnamaKelas.setText(nama);
    }


    


}
