/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JToggleButton;

/**
 *
 * @author my asus
 */
public class MhsKelasUtamaMahasiswa extends javax.swing.JFrame implements View {

    /**
     * Creates new form MenuKelasUtamaMahasiswa
     */
    public MhsKelasUtamaMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnPilihTugas = new javax.swing.JButton();
        btnGabungKelompok = new javax.swing.JButton();
        btnKelolaKelompok = new javax.swing.JButton();
        btnBack = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nama kelas disini");

        btnPilihTugas.setText("Pilih Tugas Individu");

        btnGabungKelompok.setText("Gabung ke Kelompok");

        btnKelolaKelompok.setText("Kelola Kelompok");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPilihTugas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGabungKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnKelolaKelompok, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(btnPilihTugas)
                .addGap(32, 32, 32)
                .addComponent(btnGabungKelompok)
                .addGap(31, 31, 31)
                .addComponent(btnKelolaKelompok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JToggleButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnGabungKelompok() {
        return btnGabungKelompok;
    }

    public JButton getBtnKelolaKelompok() {
        return btnKelolaKelompok;
    }

    public JButton getBtnPilihTugas() {
        return btnPilihTugas;
    }
    
    public void addListener (ActionListener l){
        btnBack.addActionListener(l);
        btnGabungKelompok.addActionListener(l);
        btnPilihTugas.addActionListener(l);
        btnKelolaKelompok.addActionListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBack;
    private javax.swing.JButton btnGabungKelompok;
    private javax.swing.JButton btnKelolaKelompok;
    private javax.swing.JButton btnPilihTugas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
