/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author my asus
 */
public class MhsLihatKelompokView extends javax.swing.JFrame implements View {

    /**
     * Creates new form MhsLihat
     */
    public MhsLihatKelompokView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNamaKelompok = new javax.swing.JLabel();
        btnInfoKelompok = new javax.swing.JButton();
        btnPilihKetua = new javax.swing.JButton();
        btnTugasKelompok = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNamaKelompok.setText("Nama Kelompok dsini");

        btnInfoKelompok.setText("Info Kelompok");

        btnPilihKetua.setText("Pilih Ketua");

        btnTugasKelompok.setText("Tugas Kelompok");

        btnBack.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(labelNamaKelompok))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnInfoKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPilihKetua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTugasKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNamaKelompok)
                .addGap(29, 29, 29)
                .addComponent(btnInfoKelompok)
                .addGap(18, 18, 18)
                .addComponent(btnPilihKetua)
                .addGap(18, 18, 18)
                .addComponent(btnTugasKelompok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnInfoKelompok() {
        return btnInfoKelompok;
    }

    public JButton getBtnPilihKetua() {
        return btnPilihKetua;
    }

    public JButton getBtnTugasKelompok() {
        return btnTugasKelompok;
    }
    
    public void addListener(ActionListener l){
        btnBack.addActionListener(l);
        btnInfoKelompok.addActionListener(l);
        btnPilihKetua.addActionListener(l);
        btnTugasKelompok.addActionListener(l);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInfoKelompok;
    private javax.swing.JButton btnPilihKetua;
    private javax.swing.JButton btnTugasKelompok;
    private javax.swing.JLabel labelNamaKelompok;
    // End of variables declaration//GEN-END:variables
}
