/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author my asus
 */
public class MhsLihatKelasView extends javax.swing.JFrame {

    /**
     * Creates new form MhsLihatKelasView
     */
    public MhsLihatKelasView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNamaKelas = new javax.swing.JLabel();
        jLabelMahasiswa = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabelDosen = new javax.swing.JLabel();
        jLabelMataKuliah = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelKelompok = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonEditKelompok = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTugasIndividu = new javax.swing.JList<>();
        jLabelDaftarTugasIndividu = new javax.swing.JLabel();
        jButtonPilihTugasIndividu = new javax.swing.JButton();
        jLabelDaftarTugasKelompok = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListTugasKelompok = new javax.swing.JList<>();
        jButtonPilihTugasKelompok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNamaKelas.setText("Nama Kelas ");

        jLabelMahasiswa.setText("Mahasiswa");

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabelDosen.setText("Dosen : ");

        jLabelMataKuliah.setText("Mata Kuliah :");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabelKelompok.setText("Kelompok :");

        jLabel8.setText("jLabel8");

        jButtonEditKelompok.setText("Edit Kelompok");
        jButtonEditKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditKelompokActionPerformed(evt);
            }
        });

        jListTugasIndividu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListTugasIndividu);

        jLabelDaftarTugasIndividu.setText("Daftar Tugas Individu ");

        jButtonPilihTugasIndividu.setText("Pilih Tugas");
        jButtonPilihTugasIndividu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihTugasIndividuActionPerformed(evt);
            }
        });

        jLabelDaftarTugasKelompok.setText("Daftar Tugas Kelompok ");

        jListTugasKelompok.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListTugasKelompok);

        jButtonPilihTugasKelompok.setText("Pilih Tugas");
        jButtonPilihTugasKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPilihTugasKelompokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMataKuliah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelKelompok)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEditKelompok))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jButtonPilihTugasIndividu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabelDaftarTugasIndividu))
                                    .addComponent(jButtonBack))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabelDaftarTugasKelompok))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jButtonPilihTugasKelompok))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMahasiswa)
                            .addComponent(jLabelNamaKelas))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNamaKelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMahasiswa)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelMataKuliah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDosen)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKelompok)
                    .addComponent(jLabel8)
                    .addComponent(jButtonEditKelompok))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDaftarTugasIndividu)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPilihTugasIndividu))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDaftarTugasKelompok)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPilihTugasKelompok)))
                .addGap(30, 30, 30)
                .addComponent(jButtonBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonEditKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditKelompokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditKelompokActionPerformed

    private void jButtonPilihTugasIndividuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihTugasIndividuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPilihTugasIndividuActionPerformed

    private void jButtonPilihTugasKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPilihTugasKelompokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPilihTugasKelompokActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonEditKelompok;
    private javax.swing.JButton jButtonPilihTugasIndividu;
    private javax.swing.JButton jButtonPilihTugasKelompok;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDaftarTugasIndividu;
    private javax.swing.JLabel jLabelDaftarTugasKelompok;
    private javax.swing.JLabel jLabelDosen;
    private javax.swing.JLabel jLabelKelompok;
    private javax.swing.JLabel jLabelMahasiswa;
    private javax.swing.JLabel jLabelMataKuliah;
    private javax.swing.JLabel jLabelNamaKelas;
    private javax.swing.JList<String> jListTugasIndividu;
    private javax.swing.JList<String> jListTugasKelompok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
