/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author ASUS
 */
public class PengelolaanKelompokDosen extends javax.swing.JFrame implements View{

    /**
     * Creates new form PengelolaanKelompokDosen
     */
    public PengelolaanKelompokDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateKelompok = new javax.swing.JButton();
        btnPilihKelompok = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateKelompok.setText("Create Kelompok Baru");
        btnCreateKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateKelompokActionPerformed(evt);
            }
        });

        btnPilihKelompok.setText("Pilih Kelompok");
        btnPilihKelompok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihKelompokActionPerformed(evt);
            }
        });

        btnBack.setText("Back");

        jLabel1.setText("Pengelolaan Kelompok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnCreateKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                .addComponent(btnPilihKelompok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(btnCreateKelompok)
                .addGap(28, 28, 28)
                .addComponent(btnPilihKelompok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihKelompokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPilihKelompokActionPerformed

    private void btnCreateKelompokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateKelompokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateKelompokActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateKelompok;
    private javax.swing.JButton btnPilihKelompok;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnBack() {
        return btnBack;
    }

    public JButton getBtnCreateKelompok() {
        return btnCreateKelompok;
    }

    public JButton getBtnPilihKelompok() {
        return btnPilihKelompok;
    }


    public void AddListener(ActionListener l){
        btnBack.addActionListener(l);
        btnPilihKelompok.addActionListener(l);
        btnCreateKelompok.addActionListener(l);
                
    
    }

}
