/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class SignUpView extends javax.swing.JFrame implements View {

    /**
     * Creates new form SignUpView
     */
    public SignUpView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupUser = new javax.swing.ButtonGroup();
        jRadioMhs = new javax.swing.JRadioButton();
        jRadioDosen = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tFUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tFPass = new javax.swing.JTextField();
        tFNama = new javax.swing.JTextField();
        tFNimNip = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        notification = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grupUser.add(jRadioMhs);
        jRadioMhs.setText("Mahasiswa");

        grupUser.add(jRadioDosen);
        jRadioDosen.setText("Dosen");
        jRadioDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDosenActionPerformed(evt);
            }
        });

        jLabel1.setText("Sign Up As: ");

        jLabel2.setText("Sign Up Menu");

        tFUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFUsernameActionPerformed(evt);
            }
        });

        jLabel3.setText("Username: ");

        jLabel4.setText("Password:");

        jLabel5.setText("Nama: ");

        jLabel6.setText("NIM / NIP :");

        tFPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFPassActionPerformed(evt);
            }
        });

        tFNimNip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNimNipActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jRadioDosen)
                        .addGap(33, 33, 33)
                        .addComponent(jRadioMhs)
                        .addGap(111, 111, 111))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tFUsername)
                            .addComponent(tFPass)
                            .addComponent(tFNama)
                            .addComponent(tFNimNip, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(notification)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioMhs)
                    .addComponent(jRadioDosen)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tFPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tFNimNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(notification)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSubmit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDosenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioDosenActionPerformed

    private void tFUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFUsernameActionPerformed

    private void tFPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFPassActionPerformed

    private void tFNimNipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNimNipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNimNipActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup grupUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioDosen;
    private javax.swing.JRadioButton jRadioMhs;
    private javax.swing.JLabel notification;
    private javax.swing.JTextField tFNama;
    private javax.swing.JTextField tFNimNip;
    private javax.swing.JTextField tFPass;
    private javax.swing.JTextField tFUsername;
    // End of variables declaration//GEN-END:variables

    
    public void addListener(ActionListener l){
        tFNama.addActionListener(l);
        tFNimNip.addActionListener(l);
        tFPass.addActionListener(l);
        tFUsername.addActionListener(l);
        
        jRadioMhs.addActionListener(l);
        jRadioDosen.addActionListener(l);
   
        
        btnCancel.addActionListener(l);
        btnSubmit.addActionListener(l);
    
    
    }

    

    public void setNotification(String name) {
        this.notification.setText(name);
    }
    
    
    
    public JButton getBtnCancel() {
        return btnCancel;
    }
   

    public JButton getBtnSubmit() {
        return btnSubmit;
    }

    public JRadioButton getjRadioDosen() {
        return jRadioDosen;
    }


    public JRadioButton getjRadioMhs() {
        return jRadioMhs;
    }

    public JTextField gettFNama() {
        return tFNama;
    }

    public void settFNama(String nama) {
        this.tFNama.setText(nama);
    }

    public JTextField gettFNimNip() {
        return tFNimNip;
    }

    public void settFNimNip(String ni) {
        this.tFNimNip.setText(ni);
    }

    public JTextField gettFPass() {
        return tFPass;
    }

    public void settFPass(String pass) {
        this.tFPass.setText(pass);
    }

    public JTextField gettFUsername() {
        return tFUsername;
    }

    public void settFUsername(String name) {
        this.tFUsername.setText(name);
    }
    
    
    
}
